//! # D-Bus interface proxy for: `org.bluez.obex.Client1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.obex.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.obex.Client1", assume_defaults = true)]
pub trait Client1 {
    /// CreateSession method
    fn create_session(
        &self,
        destination: &str,
        args: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// RemoveSession method
    fn remove_session(&self, session: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;
}
