//! # D-Bus interface proxy for: `org.bluez.MediaEndpoint1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.mediaendpoint1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.MediaEndpoint1", assume_defaults = true)]
pub trait MediaEndpoint1 {
    /// SetConfiguration method
    fn set_configuration(
        &self,
        endpoint: &zbus::zvariant::ObjectPath<'_>,
        properties: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// Capabilities property
    #[zbus(property)]
    fn capabilities(&self) -> zbus::Result<Vec<u8>>;

    /// Codec property
    #[zbus(property)]
    fn codec(&self) -> zbus::Result<u8>;

    /// DelayReporting property
    #[zbus(property)]
    fn delay_reporting(&self) -> zbus::Result<bool>;

    /// Device property
    #[zbus(property)]
    fn device(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// UUID property
    #[zbus(property, name = "UUID")]
    fn uuid(&self) -> zbus::Result<String>;
}
