//! # D-Bus interface proxy for: `org.bluez.MediaTransport1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.mediatransport1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.MediaTransport1", assume_defaults = true)]
pub trait MediaTransport1 {
    /// Acquire method
    fn acquire(&self) -> zbus::Result<(zbus::zvariant::OwnedFd, u16, u16)>;

    /// Release method
    fn release(&self) -> zbus::Result<()>;

    /// TryAcquire method
    fn try_acquire(&self) -> zbus::Result<(zbus::zvariant::OwnedFd, u16, u16)>;

    /// Codec property
    #[zbus(property)]
    fn codec(&self) -> zbus::Result<u8>;

    /// Configuration property
    #[zbus(property)]
    fn configuration(&self) -> zbus::Result<Vec<u8>>;

    /// Delay property
    #[zbus(property)]
    fn delay(&self) -> zbus::Result<u16>;

    /// Device property
    #[zbus(property)]
    fn device(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// State property
    #[zbus(property)]
    fn state(&self) -> zbus::Result<String>;

    /// UUID property
    #[zbus(property, name = "UUID")]
    fn uuid(&self) -> zbus::Result<String>;

    /// Volume property
    #[zbus(property)]
    fn volume(&self) -> zbus::Result<u16>;
    #[zbus(property)]
    fn set_volume(&self, value: u16) -> zbus::Result<()>;
}
