//! # D-Bus interface proxy for: `org.bluez.MediaItem1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.mediaitem1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.MediaItem1", assume_defaults = true)]
pub trait MediaItem1 {
    /// AddtoNowPlaying method
    fn addto_now_playing(&self) -> zbus::Result<()>;

    /// Play method
    fn play(&self) -> zbus::Result<()>;

    /// FolderType property
    #[zbus(property)]
    fn folder_type(&self) -> zbus::Result<String>;

    /// Metadata property
    #[zbus(property)]
    fn metadata(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// Playable property
    #[zbus(property)]
    fn playable(&self) -> zbus::Result<bool>;

    /// Player property
    #[zbus(property)]
    fn player(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Type property
    #[zbus(property)]
    fn type_(&self) -> zbus::Result<String>;
}
