//! # D-Bus interface proxy for: `org.bluez.MediaPlayer1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.mediaplayer1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.MediaPlayer1", assume_defaults = true)]
pub trait MediaPlayer1 {
    /// FastForward method
    fn fast_forward(&self) -> zbus::Result<()>;

    /// Hold method
    fn hold(&self, avc_key: u8) -> zbus::Result<()>;

    /// Next method
    fn next(&self) -> zbus::Result<()>;

    /// Pause method
    fn pause(&self) -> zbus::Result<()>;

    /// Play method
    fn play(&self) -> zbus::Result<()>;

    /// Press method
    fn press(&self, avc_key: u8) -> zbus::Result<()>;

    /// Previous method
    fn previous(&self) -> zbus::Result<()>;

    /// Release method
    fn release(&self) -> zbus::Result<()>;

    /// Rewind method
    fn rewind(&self) -> zbus::Result<()>;

    /// Stop method
    fn stop(&self) -> zbus::Result<()>;

    /// Browsable property
    #[zbus(property)]
    fn browsable(&self) -> zbus::Result<bool>;

    /// Device property
    #[zbus(property)]
    fn device(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Equalizer property
    #[zbus(property)]
    fn equalizer(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_equalizer(&self, value: &str) -> zbus::Result<()>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// Playlist property
    #[zbus(property)]
    fn playlist(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Position property
    #[zbus(property)]
    fn position(&self) -> zbus::Result<u32>;

    /// Repeat property
    #[zbus(property)]
    fn repeat(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_repeat(&self, value: &str) -> zbus::Result<()>;

    /// Scan property
    #[zbus(property)]
    fn scan(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_scan(&self, value: &str) -> zbus::Result<()>;

    /// Searchable property
    #[zbus(property)]
    fn searchable(&self) -> zbus::Result<bool>;

    /// Shuffle property
    #[zbus(property)]
    fn shuffle(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_shuffle(&self, value: &str) -> zbus::Result<()>;

    /// Status property
    #[zbus(property)]
    fn status(&self) -> zbus::Result<String>;

    /// Subtype property
    #[zbus(property)]
    fn subtype(&self) -> zbus::Result<String>;

    /// Track property
    #[zbus(property)]
    fn track(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Type property
    #[zbus(property)]
    fn type_(&self) -> zbus::Result<String>;
}
