//! # D-Bus interface proxy for: `org.bluez.obex.PhonebookAccess1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.obex.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.obex.PhonebookAccess1", assume_defaults = true)]
pub trait PhonebookAccess1 {
    /// GetSize method
    fn get_size(&self) -> zbus::Result<u16>;

    /// List method
    fn list(
        &self,
        filters: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<Vec<(String, String)>>;

    /// ListFilterFields method
    fn list_filter_fields(&self) -> zbus::Result<Vec<String>>;

    /// Pull method
    fn pull(
        &self,
        vcard: &str,
        targetfile: &str,
        filters: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
    )>;

    /// PullAll method
    fn pull_all(
        &self,
        targetfile: &str,
        filters: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
    )>;

    /// Search method
    fn search(
        &self,
        field: &str,
        value: &str,
        filters: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<Vec<(String, String)>>;

    /// Select method
    fn select(&self, location: &str, phonebook: &str) -> zbus::Result<()>;

    /// UpdateVersion method
    fn update_version(&self) -> zbus::Result<()>;

    /// DatabaseIdentifier property
    #[zbus(property)]
    fn database_identifier(&self) -> zbus::Result<String>;

    /// FixedImageSize property
    #[zbus(property)]
    fn fixed_image_size(&self) -> zbus::Result<bool>;

    /// Folder property
    #[zbus(property)]
    fn folder(&self) -> zbus::Result<String>;

    /// PrimaryCounter property
    #[zbus(property)]
    fn primary_counter(&self) -> zbus::Result<String>;

    /// SecondaryCounter property
    #[zbus(property)]
    fn secondary_counter(&self) -> zbus::Result<String>;
}
