//! # D-Bus interface proxy for: `org.bluez.obex.Session1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.obex.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.obex.Session1", assume_defaults = true)]
pub trait Session1 {
    /// GetCapabilities method
    fn get_capabilities(&self) -> zbus::Result<String>;

    /// Channel property
    #[zbus(property)]
    fn channel(&self) -> zbus::Result<u8>;

    /// Destination property
    #[zbus(property)]
    fn destination(&self) -> zbus::Result<String>;

    /// Source property
    #[zbus(property)]
    fn source(&self) -> zbus::Result<String>;

    /// Target property
    #[zbus(property)]
    fn target(&self) -> zbus::Result<String>;
}
