//! # D-Bus interface proxy for: `org.bluez.obex.Transfer1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.bluez.obex.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.bluez.obex.Transfer1", assume_defaults = true)]
pub trait Transfer1 {
    /// Cancel method
    fn cancel(&self) -> zbus::Result<()>;

    /// Resume method
    fn resume(&self) -> zbus::Result<()>;

    /// Suspend method
    fn suspend(&self) -> zbus::Result<()>;

    /// Filename property
    #[zbus(property)]
    fn filename(&self) -> zbus::Result<String>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// Session property
    #[zbus(property)]
    fn session(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Size property
    #[zbus(property)]
    fn size(&self) -> zbus::Result<u64>;

    /// Status property
    #[zbus(property)]
    fn status(&self) -> zbus::Result<String>;

    /// Time property
    #[zbus(property)]
    fn time(&self) -> zbus::Result<u64>;

    /// Transferred property
    #[zbus(property)]
    fn transferred(&self) -> zbus::Result<u64>;

    /// Type property
    #[zbus(property)]
    fn type_(&self) -> zbus::Result<String>;
}
